// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: suggestions/suggestions.proto

package suggestions

import (
	common "github.com/JuanGQCadavid/ds-practice-2025/utils/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemsBought struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemsBought_Item    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsBought) Reset() {
	*x = ItemsBought{}
	mi := &file_suggestions_suggestions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsBought) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsBought) ProtoMessage() {}

func (x *ItemsBought) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_suggestions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsBought.ProtoReflect.Descriptor instead.
func (*ItemsBought) Descriptor() ([]byte, []int) {
	return file_suggestions_suggestions_proto_rawDescGZIP(), []int{0}
}

func (x *ItemsBought) GetItems() []*ItemsBought_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BookSuggest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BookSuggest_Book    `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSuggest) Reset() {
	*x = BookSuggest{}
	mi := &file_suggestions_suggestions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSuggest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSuggest) ProtoMessage() {}

func (x *BookSuggest) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_suggestions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSuggest.ProtoReflect.Descriptor instead.
func (*BookSuggest) Descriptor() ([]byte, []int) {
	return file_suggestions_suggestions_proto_rawDescGZIP(), []int{1}
}

func (x *BookSuggest) GetBooks() []*BookSuggest_Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type ItemsBought_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsBought_Item) Reset() {
	*x = ItemsBought_Item{}
	mi := &file_suggestions_suggestions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsBought_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsBought_Item) ProtoMessage() {}

func (x *ItemsBought_Item) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_suggestions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsBought_Item.ProtoReflect.Descriptor instead.
func (*ItemsBought_Item) Descriptor() ([]byte, []int) {
	return file_suggestions_suggestions_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ItemsBought_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemsBought_Item) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type BookSuggest_Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSuggest_Book) Reset() {
	*x = BookSuggest_Book{}
	mi := &file_suggestions_suggestions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSuggest_Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSuggest_Book) ProtoMessage() {}

func (x *BookSuggest_Book) ProtoReflect() protoreflect.Message {
	mi := &file_suggestions_suggestions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSuggest_Book.ProtoReflect.Descriptor instead.
func (*BookSuggest_Book) Descriptor() ([]byte, []int) {
	return file_suggestions_suggestions_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BookSuggest_Book) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *BookSuggest_Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookSuggest_Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_suggestions_suggestions_proto protoreflect.FileDescriptor

var file_suggestions_suggestions_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x75,
	0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7a, 0x0a, 0x0b, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x6f, 0x75, 0x67, 0x68, 0x74,
	0x12, 0x33, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x42, 0x6f, 0x75, 0x67, 0x68, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x36, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x90, 0x01,
	0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a,
	0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x1a, 0x4c, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f,
	0x6f, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x32, 0x94, 0x01, 0x0a, 0x16, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x69,
	0x6e, 0x69, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x73, 0x12, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x6f, 0x75, 0x67, 0x68, 0x74, 0x1a, 0x18, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x61, 0x6e, 0x47, 0x51, 0x43, 0x61, 0x64, 0x61,
	0x76, 0x69, 0x64, 0x2f, 0x64, 0x73, 0x2d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x2d,
	0x32, 0x30, 0x32, 0x35, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x75,
	0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_suggestions_suggestions_proto_rawDescOnce sync.Once
	file_suggestions_suggestions_proto_rawDescData []byte
)

func file_suggestions_suggestions_proto_rawDescGZIP() []byte {
	file_suggestions_suggestions_proto_rawDescOnce.Do(func() {
		file_suggestions_suggestions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_suggestions_suggestions_proto_rawDesc), len(file_suggestions_suggestions_proto_rawDesc)))
	})
	return file_suggestions_suggestions_proto_rawDescData
}

var file_suggestions_suggestions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_suggestions_suggestions_proto_goTypes = []any{
	(*ItemsBought)(nil),         // 0: transaction.ItemsBought
	(*BookSuggest)(nil),         // 1: transaction.BookSuggest
	(*ItemsBought_Item)(nil),    // 2: transaction.ItemsBought.Item
	(*BookSuggest_Book)(nil),    // 3: transaction.BookSuggest.Book
	(*common.InitRequest)(nil),  // 4: common.InitRequest
	(*common.InitResponse)(nil), // 5: common.InitResponse
}
var file_suggestions_suggestions_proto_depIdxs = []int32{
	2, // 0: transaction.ItemsBought.items:type_name -> transaction.ItemsBought.Item
	3, // 1: transaction.BookSuggest.books:type_name -> transaction.BookSuggest.Book
	4, // 2: transaction.BookSuggestionsService.initOrder:input_type -> common.InitRequest
	0, // 3: transaction.BookSuggestionsService.suggestBooks:input_type -> transaction.ItemsBought
	5, // 4: transaction.BookSuggestionsService.initOrder:output_type -> common.InitResponse
	1, // 5: transaction.BookSuggestionsService.suggestBooks:output_type -> transaction.BookSuggest
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_suggestions_suggestions_proto_init() }
func file_suggestions_suggestions_proto_init() {
	if File_suggestions_suggestions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_suggestions_suggestions_proto_rawDesc), len(file_suggestions_suggestions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_suggestions_suggestions_proto_goTypes,
		DependencyIndexes: file_suggestions_suggestions_proto_depIdxs,
		MessageInfos:      file_suggestions_suggestions_proto_msgTypes,
	}.Build()
	File_suggestions_suggestions_proto = out.File
	file_suggestions_suggestions_proto_goTypes = nil
	file_suggestions_suggestions_proto_depIdxs = nil
}
