{
 "title": "Orchestator",
 "time": { "from": "2025-05-24T15:48:51.251Z", "to": "2025-05-24T16:48:51.251Z" },
 "panels": [
  {
   "title": "Server request size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(http_server_request_size_bytes_total{service_name=\"orchestrator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "200 vs 400",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_response_size_bytes_total{service_name=\"orchestrator\", http_status_code=\"200\"}"
    },
    {
     "expr": "http_server_response_size_bytes_total{service_name=\"orchestrator\", http_status_code=\"400\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checkout Span",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "ad6f3526", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "orchestrator" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "/checkout" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ds-practice-2025-orchestrator_v2-1\"} | json | path = `/checkout` | status > 299"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum{}[$__rate_interval]) )/sum(rate(http_server_duration_milliseconds_count{}[$__rate_interval]) )",
     "legendFormat": "http_server_duration_milliseconds (average)"
    }
   ]
  },
  {
   "title": "/checkout logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ds-practice-2025-orchestrator_v2-1\"} | json | path = `/checkout`"
    }
   ]
  }
 ]
}