# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection/fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection/fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%fraud_detection/fraud_detection.proto\x12\x05\x66raud\x1a\x13\x63ommon/common.proto\"J\n\x19\x46raudDetectionRequestInit\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x1c\n\x05order\x18\x02 \x01(\x0b\x32\r.common.Order\"<\n\x1a\x46raudDetectionRequestClock\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\r\n\x05\x63lock\x18\x02 \x03(\x05\"&\n\x16\x46raudDetectionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"]\n\x1b\x46raudDetectionResponseClock\x12/\n\x08response\x18\x01 \x01(\x0b\x32\x1d.fraud.FraudDetectionResponse\x12\r\n\x05\x63lock\x18\x02 \x03(\x05\x32\xfd\x01\n\x15\x46raudDetectionService\x12\x36\n\tinitOrder\x12\x13.common.InitRequest\x1a\x14.common.InitResponse\x12R\n\tcheckUser\x12!.fraud.FraudDetectionRequestClock\x1a\".fraud.FraudDetectionResponseClock\x12X\n\x0f\x63heckCreditCard\x12!.fraud.FraudDetectionRequestClock\x1a\".fraud.FraudDetectionResponseClockBDZBgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/fraud_detectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection.fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/fraud_detection'
  _globals['_FRAUDDETECTIONREQUESTINIT']._serialized_start=69
  _globals['_FRAUDDETECTIONREQUESTINIT']._serialized_end=143
  _globals['_FRAUDDETECTIONREQUESTCLOCK']._serialized_start=145
  _globals['_FRAUDDETECTIONREQUESTCLOCK']._serialized_end=205
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=207
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=245
  _globals['_FRAUDDETECTIONRESPONSECLOCK']._serialized_start=247
  _globals['_FRAUDDETECTIONRESPONSECLOCK']._serialized_end=340
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=343
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=596
# @@protoc_insertion_point(module_scope)
