# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05\x66raud\"%\n\x15\x46raudDetectionRequest\x12\x0c\n\x04json\x18\x01 \x01(\t\"&\n\x16\x46raudDetectionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t2b\n\x15\x46raudDetectionService\x12I\n\ncheckFraud\x12\x1c.fraud.FraudDetectionRequest\x1a\x1d.fraud.FraudDetectionResponseBDZBgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/fraud_detectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/fraud_detection'
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=32
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=69
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=71
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=109
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=111
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
