// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: utils/pb/fraud_detection/fraud_detection.proto

package fraud_detection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraudDetectionService_CheckFraud_FullMethodName = "/fraud.FraudDetectionService/checkFraud"
)

// FraudDetectionServiceClient is the client API for FraudDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudDetectionServiceClient interface {
	CheckFraud(ctx context.Context, in *FraudDetectionRequest, opts ...grpc.CallOption) (*FraudDetectionResponse, error)
}

type fraudDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudDetectionServiceClient(cc grpc.ClientConnInterface) FraudDetectionServiceClient {
	return &fraudDetectionServiceClient{cc}
}

func (c *fraudDetectionServiceClient) CheckFraud(ctx context.Context, in *FraudDetectionRequest, opts ...grpc.CallOption) (*FraudDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FraudDetectionResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_CheckFraud_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudDetectionServiceServer is the server API for FraudDetectionService service.
// All implementations must embed UnimplementedFraudDetectionServiceServer
// for forward compatibility.
type FraudDetectionServiceServer interface {
	CheckFraud(context.Context, *FraudDetectionRequest) (*FraudDetectionResponse, error)
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

// UnimplementedFraudDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraudDetectionServiceServer struct{}

func (UnimplementedFraudDetectionServiceServer) CheckFraud(context.Context, *FraudDetectionRequest) (*FraudDetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFraud not implemented")
}
func (UnimplementedFraudDetectionServiceServer) mustEmbedUnimplementedFraudDetectionServiceServer() {}
func (UnimplementedFraudDetectionServiceServer) testEmbeddedByValue()                               {}

// UnsafeFraudDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudDetectionServiceServer will
// result in compilation errors.
type UnsafeFraudDetectionServiceServer interface {
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

func RegisterFraudDetectionServiceServer(s grpc.ServiceRegistrar, srv FraudDetectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedFraudDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraudDetectionService_ServiceDesc, srv)
}

func _FraudDetectionService_CheckFraud_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FraudDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).CheckFraud(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_CheckFraud_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).CheckFraud(ctx, req.(*FraudDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudDetectionService_ServiceDesc is the grpc.ServiceDesc for FraudDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.FraudDetectionService",
	HandlerType: (*FraudDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkFraud",
			Handler:    _FraudDetectionService_CheckFraud_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "utils/pb/fraud_detection/fraud_detection.proto",
}
