// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: utils/pb/fraud_detection/fraud_detection.proto

package fraud_detection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudDetectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudDetectionRequest) Reset() {
	*x = FraudDetectionRequest{}
	mi := &file_utils_pb_fraud_detection_fraud_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudDetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudDetectionRequest) ProtoMessage() {}

func (x *FraudDetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_utils_pb_fraud_detection_fraud_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudDetectionRequest.ProtoReflect.Descriptor instead.
func (*FraudDetectionRequest) Descriptor() ([]byte, []int) {
	return file_utils_pb_fraud_detection_fraud_detection_proto_rawDescGZIP(), []int{0}
}

func (x *FraudDetectionRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type FraudDetectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudDetectionResponse) Reset() {
	*x = FraudDetectionResponse{}
	mi := &file_utils_pb_fraud_detection_fraud_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudDetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudDetectionResponse) ProtoMessage() {}

func (x *FraudDetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_utils_pb_fraud_detection_fraud_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudDetectionResponse.ProtoReflect.Descriptor instead.
func (*FraudDetectionResponse) Descriptor() ([]byte, []int) {
	return file_utils_pb_fraud_detection_fraud_detection_proto_rawDescGZIP(), []int{1}
}

func (x *FraudDetectionResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_utils_pb_fraud_detection_fraud_detection_proto protoreflect.FileDescriptor

var file_utils_pb_fraud_detection_fraud_detection_proto_rawDesc = string([]byte{
	0x0a, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x72, 0x61, 0x75, 0x64,
	0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x66, 0x72, 0x61, 0x75, 0x64,
	0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x66, 0x72, 0x61, 0x75, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x46, 0x72, 0x61, 0x75, 0x64,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6a, 0x73, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x16, 0x46, 0x72, 0x61, 0x75, 0x64, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x32, 0x62, 0x0a, 0x15, 0x46, 0x72, 0x61, 0x75, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x46, 0x72, 0x61, 0x75, 0x64, 0x12, 0x1c, 0x2e, 0x66, 0x72, 0x61, 0x75,
	0x64, 0x2e, 0x46, 0x72, 0x61, 0x75, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x72, 0x61, 0x75, 0x64, 0x2e,
	0x46, 0x72, 0x61, 0x75, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x61, 0x6e, 0x47, 0x51, 0x43, 0x61, 0x64, 0x61, 0x76,
	0x69, 0x64, 0x2f, 0x64, 0x73, 0x2d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x2d, 0x32,
	0x30, 0x32, 0x35, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x72, 0x61,
	0x75, 0x64, 0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_utils_pb_fraud_detection_fraud_detection_proto_rawDescOnce sync.Once
	file_utils_pb_fraud_detection_fraud_detection_proto_rawDescData []byte
)

func file_utils_pb_fraud_detection_fraud_detection_proto_rawDescGZIP() []byte {
	file_utils_pb_fraud_detection_fraud_detection_proto_rawDescOnce.Do(func() {
		file_utils_pb_fraud_detection_fraud_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utils_pb_fraud_detection_fraud_detection_proto_rawDesc), len(file_utils_pb_fraud_detection_fraud_detection_proto_rawDesc)))
	})
	return file_utils_pb_fraud_detection_fraud_detection_proto_rawDescData
}

var file_utils_pb_fraud_detection_fraud_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_utils_pb_fraud_detection_fraud_detection_proto_goTypes = []any{
	(*FraudDetectionRequest)(nil),  // 0: fraud.FraudDetectionRequest
	(*FraudDetectionResponse)(nil), // 1: fraud.FraudDetectionResponse
}
var file_utils_pb_fraud_detection_fraud_detection_proto_depIdxs = []int32{
	0, // 0: fraud.FraudDetectionService.checkFraud:input_type -> fraud.FraudDetectionRequest
	1, // 1: fraud.FraudDetectionService.checkFraud:output_type -> fraud.FraudDetectionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_utils_pb_fraud_detection_fraud_detection_proto_init() }
func file_utils_pb_fraud_detection_fraud_detection_proto_init() {
	if File_utils_pb_fraud_detection_fraud_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utils_pb_fraud_detection_fraud_detection_proto_rawDesc), len(file_utils_pb_fraud_detection_fraud_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_utils_pb_fraud_detection_fraud_detection_proto_goTypes,
		DependencyIndexes: file_utils_pb_fraud_detection_fraud_detection_proto_depIdxs,
		MessageInfos:      file_utils_pb_fraud_detection_fraud_detection_proto_msgTypes,
	}.Build()
	File_utils_pb_fraud_detection_fraud_detection_proto = out.File
	file_utils_pb_fraud_detection_fraud_detection_proto_goTypes = nil
	file_utils_pb_fraud_detection_fraud_detection_proto_depIdxs = nil
}
