# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection/fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection/fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%fraud_detection/fraud_detection.proto\x12\x05\x66raud\x1a\x13\x63ommon/common.proto2\xfe\x01\n\x15\x46raudDetectionService\x12\x36\n\tinitOrder\x12\x13.common.InitRequest\x1a\x14.common.InitResponse\x12\x36\n\tcheckUser\x12\x13.common.NextRequest\x1a\x14.common.NextResponse\x12<\n\x0f\x63heckCreditCard\x12\x13.common.NextRequest\x1a\x14.common.NextResponse\x12\x37\n\ncleanOrder\x12\x13.common.NextRequest\x1a\x14.common.NextResponseBDZBgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/fraud_detectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection.fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/fraud_detection'
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=70
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
