// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: fraud_detection/fraud_detection.proto

package fraud_detection

import (
	context "context"
	common "github.com/JuanGQCadavid/ds-practice-2025/utils/pb/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraudDetectionService_InitOrder_FullMethodName       = "/fraud.FraudDetectionService/initOrder"
	FraudDetectionService_CheckUser_FullMethodName       = "/fraud.FraudDetectionService/checkUser"
	FraudDetectionService_CheckCreditCard_FullMethodName = "/fraud.FraudDetectionService/checkCreditCard"
	FraudDetectionService_CleanOrder_FullMethodName      = "/fraud.FraudDetectionService/cleanOrder"
)

// FraudDetectionServiceClient is the client API for FraudDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudDetectionServiceClient interface {
	InitOrder(ctx context.Context, in *common.InitRequest, opts ...grpc.CallOption) (*common.InitResponse, error)
	CheckUser(ctx context.Context, in *common.NextRequest, opts ...grpc.CallOption) (*common.NextResponse, error)
	CheckCreditCard(ctx context.Context, in *common.NextRequest, opts ...grpc.CallOption) (*common.NextResponse, error)
	CleanOrder(ctx context.Context, in *common.NextRequest, opts ...grpc.CallOption) (*common.NextResponse, error)
}

type fraudDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudDetectionServiceClient(cc grpc.ClientConnInterface) FraudDetectionServiceClient {
	return &fraudDetectionServiceClient{cc}
}

func (c *fraudDetectionServiceClient) InitOrder(ctx context.Context, in *common.InitRequest, opts ...grpc.CallOption) (*common.InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.InitResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_InitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fraudDetectionServiceClient) CheckUser(ctx context.Context, in *common.NextRequest, opts ...grpc.CallOption) (*common.NextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.NextResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_CheckUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fraudDetectionServiceClient) CheckCreditCard(ctx context.Context, in *common.NextRequest, opts ...grpc.CallOption) (*common.NextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.NextResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_CheckCreditCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fraudDetectionServiceClient) CleanOrder(ctx context.Context, in *common.NextRequest, opts ...grpc.CallOption) (*common.NextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.NextResponse)
	err := c.cc.Invoke(ctx, FraudDetectionService_CleanOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudDetectionServiceServer is the server API for FraudDetectionService service.
// All implementations must embed UnimplementedFraudDetectionServiceServer
// for forward compatibility.
type FraudDetectionServiceServer interface {
	InitOrder(context.Context, *common.InitRequest) (*common.InitResponse, error)
	CheckUser(context.Context, *common.NextRequest) (*common.NextResponse, error)
	CheckCreditCard(context.Context, *common.NextRequest) (*common.NextResponse, error)
	CleanOrder(context.Context, *common.NextRequest) (*common.NextResponse, error)
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

// UnimplementedFraudDetectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraudDetectionServiceServer struct{}

func (UnimplementedFraudDetectionServiceServer) InitOrder(context.Context, *common.InitRequest) (*common.InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitOrder not implemented")
}
func (UnimplementedFraudDetectionServiceServer) CheckUser(context.Context, *common.NextRequest) (*common.NextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUser not implemented")
}
func (UnimplementedFraudDetectionServiceServer) CheckCreditCard(context.Context, *common.NextRequest) (*common.NextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCreditCard not implemented")
}
func (UnimplementedFraudDetectionServiceServer) CleanOrder(context.Context, *common.NextRequest) (*common.NextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanOrder not implemented")
}
func (UnimplementedFraudDetectionServiceServer) mustEmbedUnimplementedFraudDetectionServiceServer() {}
func (UnimplementedFraudDetectionServiceServer) testEmbeddedByValue()                               {}

// UnsafeFraudDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudDetectionServiceServer will
// result in compilation errors.
type UnsafeFraudDetectionServiceServer interface {
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

func RegisterFraudDetectionServiceServer(s grpc.ServiceRegistrar, srv FraudDetectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedFraudDetectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraudDetectionService_ServiceDesc, srv)
}

func _FraudDetectionService_InitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).InitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_InitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).InitOrder(ctx, req.(*common.InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FraudDetectionService_CheckUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).CheckUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_CheckUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).CheckUser(ctx, req.(*common.NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FraudDetectionService_CheckCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).CheckCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_CheckCreditCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).CheckCreditCard(ctx, req.(*common.NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FraudDetectionService_CleanOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).CleanOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudDetectionService_CleanOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).CleanOrder(ctx, req.(*common.NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudDetectionService_ServiceDesc is the grpc.ServiceDesc for FraudDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.FraudDetectionService",
	HandlerType: (*FraudDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initOrder",
			Handler:    _FraudDetectionService_InitOrder_Handler,
		},
		{
			MethodName: "checkUser",
			Handler:    _FraudDetectionService_CheckUser_Handler,
		},
		{
			MethodName: "checkCreditCard",
			Handler:    _FraudDetectionService_CheckCreditCard_Handler,
		},
		{
			MethodName: "cleanOrder",
			Handler:    _FraudDetectionService_CleanOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fraud_detection/fraud_detection.proto",
}
