# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database/database.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61tabase/database.proto\x12\x08\x64\x61tabase\"\x1e\n\x0bInitRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\x0cInitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07isValid\x18\x02 \x01(\x08\"C\n\x0cStockRequest\x12\x0e\n\x06\x62ookID\x18\x01 \x01(\t\x12\x10\n\x08\x62ookName\x18\x02 \x01(\t\x12\x11\n\tbookStock\x18\x03 \x01(\x05\"k\n\rStockResponse\x12\x10\n\x08\x62ookName\x18\x01 \x01(\t\x12\x11\n\tbookStock\x18\x02 \x01(\x05\x12\x0f\n\x07isValid\x18\x03 \x01(\x08\x12\x12\n\nerrMessage\x18\x04 \x01(\t\x12\x10\n\x08leaderID\x18\x05 \x01(\x03\"b\n\x12ReplicationRequest\x12\x0e\n\x06\x62ookID\x18\x01 \x01(\t\x12\x10\n\x08\x62ookName\x18\x02 \x01(\t\x12\x11\n\tbookStock\x18\x03 \x01(\x05\x12\x17\n\x0fsourceReplicaID\x18\x04 \x01(\x03\":\n\x13ReplicationResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x12\x12\n\nerrMessage\x18\x02 \x01(\t\"G\n\x0eStatusResponse\x12\x10\n\x08isLeader\x18\x01 \x01(\x08\x12\x11\n\treplicaID\x18\x02 \x01(\x03\x12\x10\n\x08leaderID\x18\x03 \x01(\x03\"\x0e\n\x0c\x45mptyRequest2\xe8\x02\n\x0f\x44\x61tabaseService\x12<\n\x0binitReplica\x12\x15.database.InitRequest\x1a\x16.database.InitResponse\x12\x43\n\x10performStockRead\x12\x16.database.StockRequest\x1a\x17.database.StockResponse\x12\x44\n\x11performStockWrite\x12\x16.database.StockRequest\x1a\x17.database.StockResponse\x12M\n\x0ereplicateWrite\x12\x1c.database.ReplicationRequest\x1a\x1d.database.ReplicationResponse\x12=\n\tgetStatus\x12\x16.database.EmptyRequest\x1a\x18.database.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database.database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITREQUEST']._serialized_start=37
  _globals['_INITREQUEST']._serialized_end=67
  _globals['_INITRESPONSE']._serialized_start=69
  _globals['_INITRESPONSE']._serialized_end=117
  _globals['_STOCKREQUEST']._serialized_start=119
  _globals['_STOCKREQUEST']._serialized_end=186
  _globals['_STOCKRESPONSE']._serialized_start=188
  _globals['_STOCKRESPONSE']._serialized_end=295
  _globals['_REPLICATIONREQUEST']._serialized_start=297
  _globals['_REPLICATIONREQUEST']._serialized_end=395
  _globals['_REPLICATIONRESPONSE']._serialized_start=397
  _globals['_REPLICATIONRESPONSE']._serialized_end=455
  _globals['_STATUSRESPONSE']._serialized_start=457
  _globals['_STATUSRESPONSE']._serialized_end=528
  _globals['_EMPTYREQUEST']._serialized_start=530
  _globals['_EMPTYREQUEST']._serialized_end=544
  _globals['_DATABASESERVICE']._serialized_start=547
  _globals['_DATABASESERVICE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
