# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dorder_queue/order_queue.proto\x12\x05queue\x1a\x13\x63ommon/common.proto2\xe6\x01\n\x11OrderQueueService\x12\x31\n\x04init\x12\x13.common.InitRequest\x1a\x14.common.InitResponse\x12\x34\n\x07\x65nqueue\x12\x13.common.NextRequest\x1a\x14.common.NextResponse\x12\x34\n\x07\x64\x65queue\x12\x13.common.NextRequest\x1a\x14.common.NextResponse\x12\x32\n\x05\x63lean\x12\x13.common.NextRequest\x1a\x14.common.NextResponseB@Z>github.com/JuanGQCadavid/ds-practice-2025/utils/pb/order_queueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/JuanGQCadavid/ds-practice-2025/utils/pb/order_queue'
  _globals['_ORDERQUEUESERVICE']._serialized_start=62
  _globals['_ORDERQUEUESERVICE']._serialized_end=292
# @@protoc_insertion_point(module_scope)
