// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: pb/transaction_verification/transaction_verification.proto

package transaction_verification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // first field of message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionVerificationRequest) Reset() {
	*x = TransactionVerificationRequest{}
	mi := &file_pb_transaction_verification_transaction_verification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionVerificationRequest) ProtoMessage() {}

func (x *TransactionVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_transaction_verification_transaction_verification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionVerificationRequest.ProtoReflect.Descriptor instead.
func (*TransactionVerificationRequest) Descriptor() ([]byte, []int) {
	return file_pb_transaction_verification_transaction_verification_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionVerificationRequest) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type TransactionVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionVerificationResponse) Reset() {
	*x = TransactionVerificationResponse{}
	mi := &file_pb_transaction_verification_transaction_verification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionVerificationResponse) ProtoMessage() {}

func (x *TransactionVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_transaction_verification_transaction_verification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionVerificationResponse.ProtoReflect.Descriptor instead.
func (*TransactionVerificationResponse) Descriptor() ([]byte, []int) {
	return file_pb_transaction_verification_transaction_verification_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionVerificationResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_pb_transaction_verification_transaction_verification_proto protoreflect.FileDescriptor

var file_pb_transaction_verification_transaction_verification_proto_rawDesc = string([]byte{
	0x0a, 0x3a, 0x70, 0x62, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x1e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x22,
	0x35, 0x0a, 0x1f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x8f, 0x01, 0x0a, 0x1e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x10, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x61, 0x6e, 0x47, 0x51, 0x43, 0x61, 0x64,
	0x61, 0x76, 0x69, 0x64, 0x2f, 0x64, 0x73, 0x2d, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65,
	0x2d, 0x32, 0x30, 0x32, 0x35, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pb_transaction_verification_transaction_verification_proto_rawDescOnce sync.Once
	file_pb_transaction_verification_transaction_verification_proto_rawDescData []byte
)

func file_pb_transaction_verification_transaction_verification_proto_rawDescGZIP() []byte {
	file_pb_transaction_verification_transaction_verification_proto_rawDescOnce.Do(func() {
		file_pb_transaction_verification_transaction_verification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_transaction_verification_transaction_verification_proto_rawDesc), len(file_pb_transaction_verification_transaction_verification_proto_rawDesc)))
	})
	return file_pb_transaction_verification_transaction_verification_proto_rawDescData
}

var file_pb_transaction_verification_transaction_verification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_transaction_verification_transaction_verification_proto_goTypes = []any{
	(*TransactionVerificationRequest)(nil),  // 0: transaction.TransactionVerificationRequest
	(*TransactionVerificationResponse)(nil), // 1: transaction.TransactionVerificationResponse
}
var file_pb_transaction_verification_transaction_verification_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionVerificationService.checkTransaction:input_type -> transaction.TransactionVerificationRequest
	1, // 1: transaction.TransactionVerificationService.checkTransaction:output_type -> transaction.TransactionVerificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_transaction_verification_transaction_verification_proto_init() }
func file_pb_transaction_verification_transaction_verification_proto_init() {
	if File_pb_transaction_verification_transaction_verification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_transaction_verification_transaction_verification_proto_rawDesc), len(file_pb_transaction_verification_transaction_verification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_transaction_verification_transaction_verification_proto_goTypes,
		DependencyIndexes: file_pb_transaction_verification_transaction_verification_proto_depIdxs,
		MessageInfos:      file_pb_transaction_verification_transaction_verification_proto_msgTypes,
	}.Build()
	File_pb_transaction_verification_transaction_verification_proto = out.File
	file_pb_transaction_verification_transaction_verification_proto_goTypes = nil
	file_pb_transaction_verification_transaction_verification_proto_depIdxs = nil
}
