# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common import common_pb2 as common_dot_common__pb2


class TransactionVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.initOrder = channel.unary_unary(
                '/transaction.TransactionVerificationService/initOrder',
                request_serializer=common_dot_common__pb2.InitRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.InitResponse.FromString,
                )
        self.checkOrder = channel.unary_unary(
                '/transaction.TransactionVerificationService/checkOrder',
                request_serializer=common_dot_common__pb2.NextRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.NextResponse.FromString,
                )
        self.checkUser = channel.unary_unary(
                '/transaction.TransactionVerificationService/checkUser',
                request_serializer=common_dot_common__pb2.NextRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.NextResponse.FromString,
                )
        self.checkFormatCreditCard = channel.unary_unary(
                '/transaction.TransactionVerificationService/checkFormatCreditCard',
                request_serializer=common_dot_common__pb2.NextRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.NextResponse.FromString,
                )
        self.cleanOrder = channel.unary_unary(
                '/transaction.TransactionVerificationService/cleanOrder',
                request_serializer=common_dot_common__pb2.NextRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.NextResponse.FromString,
                )


class TransactionVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def initOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkFormatCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cleanOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'initOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.initOrder,
                    request_deserializer=common_dot_common__pb2.InitRequest.FromString,
                    response_serializer=common_dot_common__pb2.InitResponse.SerializeToString,
            ),
            'checkOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.checkOrder,
                    request_deserializer=common_dot_common__pb2.NextRequest.FromString,
                    response_serializer=common_dot_common__pb2.NextResponse.SerializeToString,
            ),
            'checkUser': grpc.unary_unary_rpc_method_handler(
                    servicer.checkUser,
                    request_deserializer=common_dot_common__pb2.NextRequest.FromString,
                    response_serializer=common_dot_common__pb2.NextResponse.SerializeToString,
            ),
            'checkFormatCreditCard': grpc.unary_unary_rpc_method_handler(
                    servicer.checkFormatCreditCard,
                    request_deserializer=common_dot_common__pb2.NextRequest.FromString,
                    response_serializer=common_dot_common__pb2.NextResponse.SerializeToString,
            ),
            'cleanOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.cleanOrder,
                    request_deserializer=common_dot_common__pb2.NextRequest.FromString,
                    response_serializer=common_dot_common__pb2.NextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction.TransactionVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def initOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionVerificationService/initOrder',
            common_dot_common__pb2.InitRequest.SerializeToString,
            common_dot_common__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionVerificationService/checkOrder',
            common_dot_common__pb2.NextRequest.SerializeToString,
            common_dot_common__pb2.NextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionVerificationService/checkUser',
            common_dot_common__pb2.NextRequest.SerializeToString,
            common_dot_common__pb2.NextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkFormatCreditCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionVerificationService/checkFormatCreditCard',
            common_dot_common__pb2.NextRequest.SerializeToString,
            common_dot_common__pb2.NextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def cleanOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction.TransactionVerificationService/cleanOrder',
            common_dot_common__pb2.NextRequest.SerializeToString,
            common_dot_common__pb2.NextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
