# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\".\n\x1eTransactionVerificationRequest\x12\x0c\n\x04json\x18\x01 \x01(\t\"F\n\x1fTransactionVerificationResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x12\x12\n\nerrMessage\x18\x02 \x01(\t2\x8f\x01\n\x1eTransactionVerificationService\x12m\n\x10\x63heckTransaction\x12+.transaction.TransactionVerificationRequest\x1a,.transaction.TransactionVerificationResponseBMZKgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/transaction_verificationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZKgithub.com/JuanGQCadavid/ds-practice-2025/utils/pb/transaction_verification'
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=47
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=93
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=95
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=165
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=168
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=311
# @@protoc_insertion_point(module_scope)
