// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: utils/pb/transaction_verification/transaction_verification.proto

package transaction_verification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionVerificationService_CheckTransaction_FullMethodName = "/transaction.TransactionVerificationService/checkTransaction"
)

// TransactionVerificationServiceClient is the client API for TransactionVerificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionVerificationServiceClient interface {
	CheckTransaction(ctx context.Context, in *TransactionVerificationRequest, opts ...grpc.CallOption) (*TransactionVerificationResponse, error)
}

type transactionVerificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionVerificationServiceClient(cc grpc.ClientConnInterface) TransactionVerificationServiceClient {
	return &transactionVerificationServiceClient{cc}
}

func (c *transactionVerificationServiceClient) CheckTransaction(ctx context.Context, in *TransactionVerificationRequest, opts ...grpc.CallOption) (*TransactionVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionVerificationResponse)
	err := c.cc.Invoke(ctx, TransactionVerificationService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionVerificationServiceServer is the server API for TransactionVerificationService service.
// All implementations must embed UnimplementedTransactionVerificationServiceServer
// for forward compatibility.
type TransactionVerificationServiceServer interface {
	CheckTransaction(context.Context, *TransactionVerificationRequest) (*TransactionVerificationResponse, error)
	mustEmbedUnimplementedTransactionVerificationServiceServer()
}

// UnimplementedTransactionVerificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionVerificationServiceServer struct{}

func (UnimplementedTransactionVerificationServiceServer) CheckTransaction(context.Context, *TransactionVerificationRequest) (*TransactionVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedTransactionVerificationServiceServer) mustEmbedUnimplementedTransactionVerificationServiceServer() {
}
func (UnimplementedTransactionVerificationServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionVerificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionVerificationServiceServer will
// result in compilation errors.
type UnsafeTransactionVerificationServiceServer interface {
	mustEmbedUnimplementedTransactionVerificationServiceServer()
}

func RegisterTransactionVerificationServiceServer(s grpc.ServiceRegistrar, srv TransactionVerificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionVerificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionVerificationService_ServiceDesc, srv)
}

func _TransactionVerificationService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionVerificationServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionVerificationService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionVerificationServiceServer).CheckTransaction(ctx, req.(*TransactionVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionVerificationService_ServiceDesc is the grpc.ServiceDesc for TransactionVerificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionVerificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionVerificationService",
	HandlerType: (*TransactionVerificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkTransaction",
			Handler:    _TransactionVerificationService_CheckTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "utils/pb/transaction_verification/transaction_verification.proto",
}
