# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment/payment.proto\x12\x07payment\x1a\x13\x63ommon/common.proto\"I\n\x0ePrepareRequest\x12\x0f\n\x07orderID\x18\x01 \x01(\t\x12&\n\ncreditCard\x18\x02 \x01(\x0b\x32\x12.common.CreditCard\" \n\rCommitRequest\x12\x0f\n\x07orderID\x18\x01 \x01(\x05\"\x1f\n\x0c\x41\x62ortRequest\x12\x0f\n\x07orderID\x18\x01 \x01(\x05\x32\xb8\x01\n\x0ePaymentService\x12\x38\n\x07prepare\x12\x17.payment.PrepareRequest\x1a\x14.common.NextResponse\x12\x36\n\x06\x63ommit\x12\x16.payment.CommitRequest\x1a\x14.common.NextResponse\x12\x34\n\x05\x61\x62ort\x12\x15.payment.AbortRequest\x1a\x14.common.NextResponseB<Z:github.com/JuanGQCadavid/ds-practice-2025/utils/pb/paymentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/JuanGQCadavid/ds-practice-2025/utils/pb/payment'
  _globals['_PREPAREREQUEST']._serialized_start=55
  _globals['_PREPAREREQUEST']._serialized_end=128
  _globals['_COMMITREQUEST']._serialized_start=130
  _globals['_COMMITREQUEST']._serialized_end=162
  _globals['_ABORTREQUEST']._serialized_start=164
  _globals['_ABORTREQUEST']._serialized_end=195
  _globals['_PAYMENTSERVICE']._serialized_start=198
  _globals['_PAYMENTSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
