# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from replica import replica_pb2 as replica_dot_replica__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replica/replica_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.shareID = channel.unary_unary(
                '/Replica/shareID',
                request_serializer=replica_dot_replica__pb2.IDRequest.SerializeToString,
                response_deserializer=replica_dot_replica__pb2.IDResponse.FromString,
                _registered_method=True)
        self.notifyNewLeader = channel.unary_unary(
                '/Replica/notifyNewLeader',
                request_serializer=replica_dot_replica__pb2.LeaderNotification.SerializeToString,
                response_deserializer=replica_dot_replica__pb2.IDResponse.FromString,
                _registered_method=True)
        self.becomeLeader = channel.unary_unary(
                '/Replica/becomeLeader',
                request_serializer=replica_dot_replica__pb2.LeaderTransfer.SerializeToString,
                response_deserializer=replica_dot_replica__pb2.IDResponse.FromString,
                _registered_method=True)
        self.heartbeat = channel.unary_unary(
                '/Replica/heartbeat',
                request_serializer=replica_dot_replica__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=replica_dot_replica__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.getStatus = channel.unary_unary(
                '/Replica/getStatus',
                request_serializer=replica_dot_replica__pb2.StatusRequest.SerializeToString,
                response_deserializer=replica_dot_replica__pb2.StatusResponse.FromString,
                _registered_method=True)


class ReplicaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def shareID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def notifyNewLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def becomeLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'shareID': grpc.unary_unary_rpc_method_handler(
                    servicer.shareID,
                    request_deserializer=replica_dot_replica__pb2.IDRequest.FromString,
                    response_serializer=replica_dot_replica__pb2.IDResponse.SerializeToString,
            ),
            'notifyNewLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.notifyNewLeader,
                    request_deserializer=replica_dot_replica__pb2.LeaderNotification.FromString,
                    response_serializer=replica_dot_replica__pb2.IDResponse.SerializeToString,
            ),
            'becomeLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.becomeLeader,
                    request_deserializer=replica_dot_replica__pb2.LeaderTransfer.FromString,
                    response_serializer=replica_dot_replica__pb2.IDResponse.SerializeToString,
            ),
            'heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.heartbeat,
                    request_deserializer=replica_dot_replica__pb2.HeartbeatRequest.FromString,
                    response_serializer=replica_dot_replica__pb2.HeartbeatResponse.SerializeToString,
            ),
            'getStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getStatus,
                    request_deserializer=replica_dot_replica__pb2.StatusRequest.FromString,
                    response_serializer=replica_dot_replica__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Replica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Replica', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replica(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def shareID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replica/shareID',
            replica_dot_replica__pb2.IDRequest.SerializeToString,
            replica_dot_replica__pb2.IDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def notifyNewLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replica/notifyNewLeader',
            replica_dot_replica__pb2.LeaderNotification.SerializeToString,
            replica_dot_replica__pb2.IDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def becomeLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replica/becomeLeader',
            replica_dot_replica__pb2.LeaderTransfer.SerializeToString,
            replica_dot_replica__pb2.IDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replica/heartbeat',
            replica_dot_replica__pb2.HeartbeatRequest.SerializeToString,
            replica_dot_replica__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replica/getStatus',
            replica_dot_replica__pb2.StatusRequest.SerializeToString,
            replica_dot_replica__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
