# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replica/replica.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15replica/replica.proto\"\x17\n\tIDRequest\x12\n\n\x02ID\x18\x01 \x01(\x03\"/\n\nIDResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x12\x10\n\x08knownIDs\x18\x02 \x03(\x03\"&\n\x12LeaderNotification\x12\x10\n\x08leaderID\x18\x01 \x01(\x03\":\n\x0eLeaderTransfer\x12\x13\n\x0boldLeaderID\x18\x01 \x01(\x03\x12\x13\n\x0bnewLeaderID\x18\x02 \x01(\x03\"$\n\x10HeartbeatRequest\x12\x10\n\x08leaderID\x18\x01 \x01(\x03\"7\n\x11HeartbeatResponse\x12\x11\n\treplicaID\x18\x01 \x01(\x03\x12\x0f\n\x07isAlive\x18\x02 \x01(\x08\"\x0f\n\rStatusRequest\"p\n\x0eStatusResponse\x12\x11\n\treplicaID\x18\x01 \x01(\x05\x12\x10\n\x08isLeader\x18\x02 \x01(\x08\x12\x0e\n\x06leader\x18\x03 \x01(\x05\x12\x12\n\nlastAccess\x18\x04 \x01(\t\x12\x15\n\rknownReplicas\x18\x05 \x03(\x05\x32\xf4\x01\n\x07Replica\x12\"\n\x07shareID\x12\n.IDRequest\x1a\x0b.IDResponse\x12\x33\n\x0fnotifyNewLeader\x12\x13.LeaderNotification\x1a\x0b.IDResponse\x12,\n\x0c\x62\x65\x63omeLeader\x12\x0f.LeaderTransfer\x1a\x0b.IDResponse\x12\x32\n\theartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\x12.\n\tgetStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replica.replica_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IDREQUEST']._serialized_start=25
  _globals['_IDREQUEST']._serialized_end=48
  _globals['_IDRESPONSE']._serialized_start=50
  _globals['_IDRESPONSE']._serialized_end=97
  _globals['_LEADERNOTIFICATION']._serialized_start=99
  _globals['_LEADERNOTIFICATION']._serialized_end=137
  _globals['_LEADERTRANSFER']._serialized_start=139
  _globals['_LEADERTRANSFER']._serialized_end=197
  _globals['_HEARTBEATREQUEST']._serialized_start=199
  _globals['_HEARTBEATREQUEST']._serialized_end=235
  _globals['_HEARTBEATRESPONSE']._serialized_start=237
  _globals['_HEARTBEATRESPONSE']._serialized_end=292
  _globals['_STATUSREQUEST']._serialized_start=294
  _globals['_STATUSREQUEST']._serialized_end=309
  _globals['_STATUSRESPONSE']._serialized_start=311
  _globals['_STATUSRESPONSE']._serialized_end=423
  _globals['_REPLICA']._serialized_start=426
  _globals['_REPLICA']._serialized_end=670
# @@protoc_insertion_point(module_scope)
